// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAllChatroomsParams creates a new GetAllChatroomsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllChatroomsParams() *GetAllChatroomsParams {
	return &GetAllChatroomsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllChatroomsParamsWithTimeout creates a new GetAllChatroomsParams object
// with the ability to set a timeout on a request.
func NewGetAllChatroomsParamsWithTimeout(timeout time.Duration) *GetAllChatroomsParams {
	return &GetAllChatroomsParams{
		timeout: timeout,
	}
}

// NewGetAllChatroomsParamsWithContext creates a new GetAllChatroomsParams object
// with the ability to set a context for a request.
func NewGetAllChatroomsParamsWithContext(ctx context.Context) *GetAllChatroomsParams {
	return &GetAllChatroomsParams{
		Context: ctx,
	}
}

// NewGetAllChatroomsParamsWithHTTPClient creates a new GetAllChatroomsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllChatroomsParamsWithHTTPClient(client *http.Client) *GetAllChatroomsParams {
	return &GetAllChatroomsParams{
		HTTPClient: client,
	}
}

/*
GetAllChatroomsParams contains all the parameters to send to the API endpoint

	for the get all chatrooms operation.

	Typically these are written to a http.Request.
*/
type GetAllChatroomsParams struct {

	// Limit.
	Limit *int64

	// Name.
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all chatrooms params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllChatroomsParams) WithDefaults() *GetAllChatroomsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all chatrooms params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllChatroomsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all chatrooms params
func (o *GetAllChatroomsParams) WithTimeout(timeout time.Duration) *GetAllChatroomsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all chatrooms params
func (o *GetAllChatroomsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all chatrooms params
func (o *GetAllChatroomsParams) WithContext(ctx context.Context) *GetAllChatroomsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all chatrooms params
func (o *GetAllChatroomsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all chatrooms params
func (o *GetAllChatroomsParams) WithHTTPClient(client *http.Client) *GetAllChatroomsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all chatrooms params
func (o *GetAllChatroomsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get all chatrooms params
func (o *GetAllChatroomsParams) WithLimit(limit *int64) *GetAllChatroomsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get all chatrooms params
func (o *GetAllChatroomsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the get all chatrooms params
func (o *GetAllChatroomsParams) WithName(name *string) *GetAllChatroomsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get all chatrooms params
func (o *GetAllChatroomsParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllChatroomsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
