// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetChatroomHandlerFunc turns a function with the right signature into a get chatroom handler
type GetChatroomHandlerFunc func(GetChatroomParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetChatroomHandlerFunc) Handle(params GetChatroomParams) middleware.Responder {
	return fn(params)
}

// GetChatroomHandler interface for that can handle valid get chatroom params
type GetChatroomHandler interface {
	Handle(GetChatroomParams) middleware.Responder
}

// NewGetChatroom creates a new http.Handler for the get chatroom operation
func NewGetChatroom(ctx *middleware.Context, handler GetChatroomHandler) *GetChatroom {
	return &GetChatroom{Context: ctx, Handler: handler}
}

/*
	GetChatroom swagger:route GET /chatrooms/{chatroom_id} service getChatroom

get chatroom base on id
*/
type GetChatroom struct {
	Context *middleware.Context
	Handler GetChatroomHandler
}

func (o *GetChatroom) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetChatroomParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
