// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/Hammad887/chat-app/docs/restapi/operations/service"
)

// NewChatroomAPI creates a new Chatroom instance
func NewChatroomAPI(spec *loads.Document) *ChatroomAPI {
	return &ChatroomAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		ServiceLoginHandler: service.LoginHandlerFunc(func(params service.LoginParams) middleware.Responder {
			return middleware.NotImplemented("operation service.Login has not yet been implemented")
		}),
		ServiceLogoutHandler: service.LogoutHandlerFunc(func(params service.LogoutParams) middleware.Responder {
			return middleware.NotImplemented("operation service.Logout has not yet been implemented")
		}),
		ServiceGetAllChatroomsHandler: service.GetAllChatroomsHandlerFunc(func(params service.GetAllChatroomsParams) middleware.Responder {
			return middleware.NotImplemented("operation service.GetAllChatrooms has not yet been implemented")
		}),
		ServiceGetAllMessagesHandler: service.GetAllMessagesHandlerFunc(func(params service.GetAllMessagesParams) middleware.Responder {
			return middleware.NotImplemented("operation service.GetAllMessages has not yet been implemented")
		}),
		ServiceGetChatroomHandler: service.GetChatroomHandlerFunc(func(params service.GetChatroomParams) middleware.Responder {
			return middleware.NotImplemented("operation service.GetChatroom has not yet been implemented")
		}),
		ServiceRegisterUserHandler: service.RegisterUserHandlerFunc(func(params service.RegisterUserParams) middleware.Responder {
			return middleware.NotImplemented("operation service.RegisterUser has not yet been implemented")
		}),
		ServiceSendMessageHandler: service.SendMessageHandlerFunc(func(params service.SendMessageParams) middleware.Responder {
			return middleware.NotImplemented("operation service.SendMessage has not yet been implemented")
		}),
	}
}

/*ChatroomAPI the chatroom API */
type ChatroomAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// ServiceLoginHandler sets the operation handler for the login operation
	ServiceLoginHandler service.LoginHandler
	// ServiceLogoutHandler sets the operation handler for the logout operation
	ServiceLogoutHandler service.LogoutHandler
	// ServiceGetAllChatroomsHandler sets the operation handler for the get all chatrooms operation
	ServiceGetAllChatroomsHandler service.GetAllChatroomsHandler
	// ServiceGetAllMessagesHandler sets the operation handler for the get all messages operation
	ServiceGetAllMessagesHandler service.GetAllMessagesHandler
	// ServiceGetChatroomHandler sets the operation handler for the get chatroom operation
	ServiceGetChatroomHandler service.GetChatroomHandler
	// ServiceRegisterUserHandler sets the operation handler for the register user operation
	ServiceRegisterUserHandler service.RegisterUserHandler
	// ServiceSendMessageHandler sets the operation handler for the send message operation
	ServiceSendMessageHandler service.SendMessageHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *ChatroomAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *ChatroomAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *ChatroomAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *ChatroomAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *ChatroomAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *ChatroomAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *ChatroomAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *ChatroomAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *ChatroomAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the ChatroomAPI
func (o *ChatroomAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ServiceLoginHandler == nil {
		unregistered = append(unregistered, "service.LoginHandler")
	}
	if o.ServiceLogoutHandler == nil {
		unregistered = append(unregistered, "service.LogoutHandler")
	}
	if o.ServiceGetAllChatroomsHandler == nil {
		unregistered = append(unregistered, "service.GetAllChatroomsHandler")
	}
	if o.ServiceGetAllMessagesHandler == nil {
		unregistered = append(unregistered, "service.GetAllMessagesHandler")
	}
	if o.ServiceGetChatroomHandler == nil {
		unregistered = append(unregistered, "service.GetChatroomHandler")
	}
	if o.ServiceRegisterUserHandler == nil {
		unregistered = append(unregistered, "service.RegisterUserHandler")
	}
	if o.ServiceSendMessageHandler == nil {
		unregistered = append(unregistered, "service.SendMessageHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *ChatroomAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *ChatroomAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *ChatroomAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *ChatroomAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *ChatroomAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *ChatroomAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the chatroom API
func (o *ChatroomAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *ChatroomAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/login"] = service.NewLogin(o.context, o.ServiceLoginHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/logout"] = service.NewLogout(o.context, o.ServiceLogoutHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/chatrooms"] = service.NewGetAllChatrooms(o.context, o.ServiceGetAllChatroomsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/chatrooms/{chatroom_id}/messages"] = service.NewGetAllMessages(o.context, o.ServiceGetAllMessagesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/chatrooms/{chatroom_id}"] = service.NewGetChatroom(o.context, o.ServiceGetChatroomHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/user"] = service.NewRegisterUser(o.context, o.ServiceRegisterUserHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/chatrooms/{chatroom_id}/messages"] = service.NewSendMessage(o.context, o.ServiceSendMessageHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *ChatroomAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *ChatroomAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *ChatroomAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *ChatroomAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *ChatroomAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
